name: Actionlint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint@v1
